enum CAR_SLOT_ID {
	CARSLOTID_MODEL_FIRST = 0,
	CARSLOTID_BASE = 0,
	CARSLOTID_VINYL_LAYER_NUM = 1,
	CARSLOTID_DAMAGE_MODEL_FIRST = 1,
	CARSLOTID_DAMAGE_FRONT_WINDOW = 1,
	CARSLOTID_DAMAGE_BODY = 2,
	CARSLOTID_DAMAGE_COP_LIGHTS = 3,
	CARSLOTID_VINYL_COLOUR_NUM = 4,
	CARSLOTID_DAMAGE_COP_SPOILER = 4,
	CARSLOTID_DAMAGE_FRONT_WHEEL = 5,
	CARSLOTID_DECAL_MODEL_NUM = 6,
	CARSLOTID_DAMAGE_PLAYER_MODEL_NUM = 6,
	CARSLOTID_DAMAGE_LEFT_BRAKELIGHT = 6,
	CARSLOTID_DAMAGE_RIGHT_BRAKELIGHT = 7,
	CARSLOTID_DAMAGE_LEFT_HEADLIGHT = 8,
	CARSLOTID_DAMAGE_RIGHT_HEADLIGHT = 9,
	CARSLOTID_DAMAGE_HOOD = 10,
	CARSLOTID_DAMAGE_BUSHGUARD = 11,
	CARSLOTID_DAMAGE_FRONT_BUMPER = 12,
	CARSLOTID_DAMAGE_RIGHT_DOOR = 13,
	CARSLOTID_DAMAGE_RIGHT_REAR_DOOR = 14,
	CARSLOTID_DAMAGE_TRUNK = 15,
	CARSLOTID_DAMAGE_REAR_BUMPER = 16,
	CARSLOTID_DAMAGE_REAR_LEFT_WINDOW = 17,
	CARSLOTID_DAMAGE_FRONT_LEFT_WINDOW = 18,
	CARSLOTID_DAMAGE_FRONT_RIGHT_WINDOW = 19,
	CARSLOTID_DAMAGE_REAR_RIGHT_WINDOW = 20,
	CARSLOTID_DAMAGE_LEFT_DOOR = 21,
	CARSLOTID_DAMAGE_LEFT_REAR_DOOR = 22,
	CARSLOTID_DAMAGE_MODEL_NUM = 23,
	CARSLOTID_DAMAGE_MODEL_LAST = 23,
	CARSLOTID_BODY = 23,
	CARSLOTID_FRONT_BRAKE = 24,
	CARSLOTID_FRONT_LEFT_WINDOW = 25,
	CARSLOTID_FRONT_RIGHT_WINDOW = 26,
	CARSLOTID_FRONT_WINDOW = 27,
	CARSLOTID_INTERIOR = 28,
	CARSLOTID_LEFT_BRAKELIGHT = 29,
	CARSLOTID_LEFT_BRAKELIGHT_GLASS = 30,
	CARSLOTID_LEFT_HEADLIGHT = 31,
	CARSLOTID_LEFT_HEADLIGHT_GLASS = 32,
	CARSLOTID_LEFT_SIDE_MIRROR = 33,
	CARSLOTID_REAR_BRAKE = 34,
	CARSLOTID_REAR_LEFT_WINDOW = 35,
	CARSLOTID_REAR_RIGHT_WINDOW = 36,
	CARSLOTID_REAR_WINDOW = 37,
	CARSLOTID_RIGHT_BRAKELIGHT = 38,
	CARSLOTID_RIGHT_BRAKELIGHT_GLASS = 39,
	CARSLOTID_RIGHT_HEADLIGHT = 40,
	CARSLOTID_RIGHT_HEADLIGHT_GLASS = 41,
	CARSLOTID_RIGHT_SIDE_MIRROR = 42,
	CARSLOTID_DRIVER = 43,
	CARSLOTID_SPOILER = 44,
	CARSLOTID_UNIVERSAL_SPOILER_BASE = 45,
	CARSLOTID_DAMAGE_PLAYER_MODEL_FIRST = 46,
	CARSLOTID_DAMAGE0_FRONT = 46,
	CARSLOTID_DAMAGE0_FRONTLEFT = 47,
	CARSLOTID_DECAL_TEXTURE_NUM = 48,
	CARSLOTID_DAMAGE0_FRONTRIGHT = 48,
	CARSLOTID_DAMAGE0_REAR = 49,
	CARSLOTID_DAMAGE0_REARLEFT = 50,
	CARSLOTID_DAMAGE_PLAYER_MODEL_LAST = 51,
	CARSLOTID_DAMAGE0_REARRIGHT = 51,
	CARSLOTID_ATTACHMENT0 = 52,
	CARSLOTID_ATTACHMENT1 = 53,
	CARSLOTID_ATTACHMENT2 = 54,
	CARSLOTID_ATTACHMENT3 = 55,
	CARSLOTID_ATTACHMENT4 = 56,
	CARSLOTID_ATTACHMENT5 = 57,
	CARSLOTID_ATTACHMENT6 = 58,
	CARSLOTID_ATTACHMENT7 = 59,
	CARSLOTID_ATTACHMENT8 = 60,
	CARSLOTID_ATTACHMENT9 = 61,
	CARSLOTID_ROOF = 62,
	CARSLOTID_HOOD = 63,
	CARSLOTID_HEADLIGHT = 64,
	CARSLOTID_BRAKELIGHT = 65,
	CARSLOTID_FRONT_WHEEL = 66,
	CARSLOTID_REAR_WHEEL = 67,
	CARSLOTID_SPINNER = 68,
	CARSLOTID_LICENSE_PLATE = 69,
	CARSLOTID_DECAL_MODEL_FIRST = 70,
	CARSLOTID_DECAL_FRONT_WINDOW = 70,
	CARSLOTID_DECAL_REAR_WINDOW = 71,
	CARSLOTID_DECAL_LEFT_DOOR = 72,
	CARSLOTID_DECAL_RIGHT_DOOR = 73,
	CARSLOTID_DECAL_LEFT_QUARTER = 74,
	CARSLOTID_DECAL_MODEL_LAST = 75,
	CARSLOTID_MODEL_LAST = 75,
	CARSLOTID_DECAL_RIGHT_QUARTER = 75,
	CARSLOTID_MODEL_NUM = 76,
	CARSLOTID_BASE_PAINT = 76,
	CARSLOTID_VINYL_LAYER_LAST = 77,
	CARSLOTID_VINYL_LAYER_FIRST = 77,
	CARSLOTID_VINYL_LAYER0 = 77,
	CARSLOTID_PAINT_RIM = 78,
	CARSLOTID_VINYL_COLOUR_FIRST = 79,
	CARSLOTID_VINYL_COLOUR0_0 = 79,
	CARSLOTID_VINYL_COLOUR0_1 = 80,
	CARSLOTID_VINYL_COLOUR0_2 = 81,
	CARSLOTID_VINYL_COLOUR_LAST = 82,
	CARSLOTID_VINYL_COLOUR0_3 = 82,
	CARSLOTID_DECAL_TEXTURE_FIRST = 83,
	CARSLOTID_DECAL_FRONT_WINDOW_TEX0 = 83,
	CARSLOTID_DECAL_FRONT_WINDOW_TEX1 = 84,
	CARSLOTID_DECAL_FRONT_WINDOW_TEX2 = 85,
	CARSLOTID_DECAL_FRONT_WINDOW_TEX3 = 86,
	CARSLOTID_DECAL_FRONT_WINDOW_TEX4 = 87,
	CARSLOTID_DECAL_FRONT_WINDOW_TEX5 = 88,
	CARSLOTID_DECAL_FRONT_WINDOW_TEX6 = 89,
	CARSLOTID_DECAL_FRONT_WINDOW_TEX7 = 90,
	CARSLOTID_DECAL_REAR_WINDOW_TEX0 = 91,
	CARSLOTID_DECAL_REAR_WINDOW_TEX1 = 92,
	CARSLOTID_DECAL_REAR_WINDOW_TEX2 = 93,
	CARSLOTID_DECAL_REAR_WINDOW_TEX3 = 94,
	CARSLOTID_DECAL_REAR_WINDOW_TEX4 = 95,
	CARSLOTID_DECAL_REAR_WINDOW_TEX5 = 96,
	CARSLOTID_DECAL_REAR_WINDOW_TEX6 = 97,
	CARSLOTID_DECAL_REAR_WINDOW_TEX7 = 98,
	CARSLOTID_DECAL_LEFT_DOOR_TEX0 = 99,
	CARSLOTID_DECAL_LEFT_DOOR_TEX1 = 100,
	CARSLOTID_DECAL_LEFT_DOOR_TEX2 = 101,
	CARSLOTID_DECAL_LEFT_DOOR_TEX3 = 102,
	CARSLOTID_DECAL_LEFT_DOOR_TEX4 = 103,
	CARSLOTID_DECAL_LEFT_DOOR_TEX5 = 104,
	CARSLOTID_DECAL_LEFT_DOOR_LNUMBER = 105,
	CARSLOTID_DECAL_LEFT_DOOR_TEX6 = 105,
	CARSLOTID_DECAL_LEFT_DOOR_RNUMBER = 106,
	CARSLOTID_DECAL_LEFT_DOOR_TEX7 = 106,
	CARSLOTID_DECAL_RIGHT_DOOR_TEX0 = 107,
	CARSLOTID_DECAL_RIGHT_DOOR_TEX1 = 108,
	CARSLOTID_DECAL_RIGHT_DOOR_TEX2 = 109,
	CARSLOTID_DECAL_RIGHT_DOOR_TEX3 = 110,
	CARSLOTID_DECAL_RIGHT_DOOR_TEX4 = 111,
	CARSLOTID_DECAL_RIGHT_DOOR_TEX5 = 112,
	CARSLOTID_DECAL_RIGHT_DOOR_LNUMBER = 113,
	CARSLOTID_DECAL_RIGHT_DOOR_TEX6 = 113,
	CARSLOTID_DECAL_RIGHT_DOOR_RNUMBER = 114,
	CARSLOTID_DECAL_RIGHT_DOOR_TEX7 = 114,
	CARSLOTID_DECAL_LEFT_QUARTER_TEX0 = 115,
	CARSLOTID_DECAL_LEFT_QUARTER_TEX1 = 116,
	CARSLOTID_DECAL_LEFT_QUARTER_TEX2 = 117,
	CARSLOTID_DECAL_LEFT_QUARTER_TEX3 = 118,
	CARSLOTID_DECAL_LEFT_QUARTER_TEX4 = 119,
	CARSLOTID_DECAL_LEFT_QUARTER_TEX5 = 120,
	CARSLOTID_DECAL_LEFT_QUARTER_TEX6 = 121,
	CARSLOTID_DECAL_LEFT_QUARTER_TEX7 = 122,
	CARSLOTID_DECAL_RIGHT_QUARTER_TEX0 = 123,
	CARSLOTID_DECAL_RIGHT_QUARTER_TEX1 = 124,
	CARSLOTID_DECAL_RIGHT_QUARTER_TEX2 = 125,
	CARSLOTID_DECAL_RIGHT_QUARTER_TEX3 = 126,
	CARSLOTID_DECAL_RIGHT_QUARTER_TEX4 = 127,
	CARSLOTID_DECAL_RIGHT_QUARTER_TEX5 = 128,
	CARSLOTID_DECAL_RIGHT_QUARTER_TEX6 = 129,
	CARSLOTID_DECAL_TEXTURE_LAST = 130,
	CARSLOTID_DECAL_RIGHT_QUARTER_TEX7 = 130,
	CARSLOTID_WINDOW_TINT = 131,
	CARSLOTID_CUSTOM_HUD = 132,
	CARSLOTID_HUD_BACKING_COLOUR = 133,
	CARSLOTID_HUD_NEEDLE_COLOUR = 134,
	CARSLOTID_HUD_CHARACTER_COLOUR = 135,
	CARSLOTID_CV = 136,
	CARSLOTID_WHEEL_MANUFACTURER = 137,
	CARSLOTID_MISC = 138,
	CARSLOTID_NUM = 139,
};

class CarPartAttributeTable;
class CarPartAttribute;
class CarPartModelTable;
class CarPart;

class CarPartPack : public bTNode<CarPartPack> {
public:
	unsigned int Version;
	const char* StringTable;
	unsigned int StringTableSize;
	CarPartAttributeTable* AttributeTableTable;
	unsigned int NumAttributeTables;
	CarPartAttribute* AttributesTable;
	unsigned int NumAttributes;
	unsigned int* TypeNameTable;
	unsigned int NumTypeNames;
	CarPartModelTable* ModelTable;
	unsigned int NumModelTables;
	CarPart* PartsTable;
	unsigned int NumParts;
};
static_assert(sizeof(CarPartPack) == 0x3C);

class CarPart {
public:
	unsigned short PartNameHashBot;
	unsigned short PartNameHashTop;
	char PartID;
	unsigned char GroupNumber_UpgradeLevel;
	char BaseModelNameHashSelector;
	unsigned char CarTypeNameHashIndex;
	unsigned short NameOffset;
	unsigned short AttributeTableOffset;
	unsigned short ModelNameHashTableOffset;

	inline uint32_t GetPartNameHash() {
		return *(uint32_t*)&PartNameHashBot;
	}
};
static_assert(sizeof(CarPart) == 0xE);

class CarPartIndex {
public:
	CarPart* Part;
	int NumParts;
};
static_assert(sizeof(CarPartIndex) == 0x8);

class CarPartDatabase {
public:
	bTList<CarPartPack> CarPartPackList;
	int NumPacks;
	int NumParts;
	int NumBytes;
	CarPartIndex PaintPart_Gloss[3];
	CarPartIndex PaintPart_Metallic[3];
	CarPartIndex PaintPart_Pearl[3];
	CarPartIndex PaintPart_Vinyl[3];
	CarPartIndex PaintPart_Rims[3];
	CarPartIndex PaintPart_Caliper[3];
	CarPartIndex VinylPart_All[3];
	CarPartIndex VinylPart_Body[3];
	CarPartIndex VinylPart_Hood[3];
	CarPartIndex VinylPart_Side[3];
	CarPartIndex VinylPart_Manufacturer[3];

	static inline auto GetCarType = (uint32_t(__thiscall*)(CarPartDatabase*, uint32_t))0x5816B0;
	static inline auto NewGetCarPart = (CarPart*(__thiscall*)(CarPartDatabase*, CarType, int, uint32_t, CarPart*, int))0x747C40;
	static inline auto GetPartIndex = (int(__thiscall*)(CarPartDatabase*, CarPart*))0x747BB0;
	static inline auto GetCarPartByIndex = (CarPart*(__thiscall*)(CarPartDatabase*, int))0x747C00;
};
static_assert(sizeof(CarPartDatabase) == 0x11C);

auto& CarPartDB = *(CarPartDatabase*)0x9B26A8;